language: c
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.6.13-linux64.tar.xz
  - tar xf arduino-1.6.13-linux64.tar.xz
  - sudo mv arduino-1.6.13 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
  #- ln -s $PWD /usr/local/share/arduino/libraries/WiFiManager
# boards manager not working on 1.6.7 - 1.6.8
 #  - arduino --pref "boardsmanager.additional.urls=http://arduino.esp8266.com/stable/package_esp8266com_index.json" --save-prefs
# install lib arduino json not working in 1.6.5
  - arduino --install-library "ArduinoJson"
  - arduino --install-library "TimerOne"
  #  - git clone https://github.com/bblanchon/ArduinoJson /usr/local/share/arduino/libraries/ArduinoJson
#  - ln -s $PWD/src/_micro-api/libraries/timerone /usr/local/share/arduino/libraries/timerone
  - ln -s $PWD/src/_micro-api/libraries/bitstore /usr/local/share/arduino/libraries/bitstore
  - ln -s $PWD/src/_micro-api/libraries/output /usr/local/share/arduino/libraries/output
  - ln -s $PWD/src/_micro-api/libraries/signalDecoder /usr/local/share/arduino/libraries/signalDecoder
  - ln -s $PWD/src/_micro-api/libraries/SimpleFIFO /usr/local/share/arduino/libraries/simpleFIFO
  - ln -s $PWD/src/_micro-api/libraries/fastdelegate /usr/local/share/arduino/libraries/fastdelegate
  - ln -s $PWD/cc1101.h $PWD/RF_Receiver/cc1101.h
  - mkdir $PWD/release
  #- arduino --install-boards arduino:avr:uno
  #- arduino --install-boards arduino:avr:nano
  - arduino --board arduino:avr:nano --save-prefs
  - arduino --pref "compiler.warning_level=all" --save-prefs
  - arduino --pref "build.path=$PWD/release" --save-prefs
script:
  - "ls -l /usr/local/share/arduino/libraries/"
  - "file /usr/local/share/arduino/libraries/*/*"
  - "echo $PWD"
  - "echo $HOME"
  - "ls $PWD"
  - arduino -v --verbose-build --verify $PWD/RF_Receiver/RF_Receiver.ino 2>&1
after_success:
#  - bash <(curl -s https://codecov.io/bash)
   - file $PWD/release/*
   - mv $PWD/release/SIGNALESP.ino.bin $PWD/release/SIGNALESP.bin
notifications:
  email:
    on_success: change
    on_failure: change
